spring.application.name=cash-api

spring.datasource.url=jdbc:mariadb://localhost:3306/cash-money-api
spring.datasource.username=cash_user
spring.datasource.password=123456
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Mostra as queries sql no terminal 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect


# usar o dialeto correto para o MariaDB

spring.flyway.enabled=true
spring.flyway.ignore-migration-limit=true
spring.flyway.user=cash_user
spring.flyway.password=123456
spring.flyway.baseline-on-migarate=true

spring.jackson.date-format=yyyy-MM-dd


