spring.application.name=cash-api

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://cash-db:3306/cash-money-api}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:cash_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

spring.flyway.enabled=true
spring.flyway.ignore-migration-limit=true
spring.flyway.user=${SPRING_DATASOURCE_USERNAME:cash_user}
spring.flyway.password=${SPRING_DATASOURCE_PASSWORD:123456}
spring.flyway.baseline-on-migrate=true

spring.jackson.date-format=yyyy-MM-dd

spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false

cashmoney.seguranca.enable-https=false


